### ISSUE TITLE
undefined method Auth::_importGlobalVariable()

### ISSUE THREAD

**Issue by rubo77** [rubo77/timeeffect#1]
@jkrogma: maybe you have an idea?

After install I get the message
```
Fatal error:  Uncaught Error: Call to undefined method Auth::_importGlobalVariable() in /var/www/timeeffect/include/auth.inc.php:116
Stack trace:
#0 /var/www/timeeffect/include/auth.inc.php(108): PJAuth-&gt;fetchAdditionalData()
#1 /var/www/timeeffect/include/auth.inc.php(222): PJAuth-&gt;__construct()
#2 /var/www/timeeffect/include/aperetiv.inc.php(166): include_once('/var/www/timeef...')
#3 /var/www/timeeffect/inventory/customer.php(2): include_once('/var/www/timeef...')
#4 {main}
  thrown in <b>/var/www/timeeffect/include/auth.inc.php</b> on line 116

```

and if I comment that out:

```

Notice: Trying to get property 'options' of non-object in /var/www/timeeffect/include/auth.inc.php on line 118

Notice: Trying to get property 'options' of non-object in /var/www/timeeffect/include/auth.inc.php on line 119

Fatal error: Uncaught Error: Call to a member function query() on string in /var/www/timeeffect/include/auth.inc.php:123 Stack trace: #0 /var/www/timeeffect/include/auth.inc.php(108): PJAuth->fetchAdditionalData() #1 /var/www/timeeffect/include/auth.inc.php(222): PJAuth->__construct() #2 /var/www/timeeffect/include/aperetiv.inc.php(166): include_once('/var/www/timeef...') #3 /var/www/timeeffect/inventory/customer.php(2): include_once('/var/www/timeef...') #4 {main} thrown in /var/www/timeeffect/include/auth.inc.php on line 123
```

**Comment by rubo77** [comment]
I found out, that I can use the old Auth class, which still has the _importGlobalVariable function
